// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiProyecto;

namespace apiProyecto.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apiProyecto.Complejo", b =>
                {
                    b.Property<int>("idComplejo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantCanchas")
                        .HasColumnName("CantidadDeCanchas")
                        .HasColumnType("int");

                    b.Property<decimal>("latitud")
                        .HasColumnName("Latitud")
                        .HasColumnType("decimal");

                    b.Property<decimal>("longitud")
                        .HasColumnName("Longitud")
                        .HasColumnType("decimal");

                    b.Property<string>("nombre")
                        .HasColumnName("Nombre")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("idComplejo");

                    b.ToTable("Complejo");
                });

            modelBuilder.Entity("apiProyecto.Models.Cancha", b =>
                {
                    b.Property<int>("idCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("complejoidComplejo")
                        .HasColumnType("int");

                    b.Property<decimal>("estado")
                        .HasColumnName("EstadoCancha")
                        .HasColumnType("decimal");

                    b.Property<int>("idComplejo")
                        .HasColumnName("idComplejo")
                        .HasColumnType("int");

                    b.Property<int>("precio")
                        .HasColumnName("Precio")
                        .HasColumnType("int");

                    b.HasKey("idCancha");

                    b.HasIndex("complejoidComplejo");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("apiProyecto.Models.Cancha", b =>
                {
                    b.HasOne("apiProyecto.Complejo", "complejo")
                        .WithMany()
                        .HasForeignKey("complejoidComplejo");
                });
#pragma warning restore 612, 618
        }
    }
}
